# Generated by Django 3.1.12 on 2025-05-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sidhant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sidhant',
        ),
    ]
