# Generated by Django 3.1.12 on 2025-05-25 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250525_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productId', models.UUIDField()),
                ('quantity', models.IntegerField()),
                ('deliveryOptionId', models.CharField(max_length=100)),
            ],
        ),
    ]
