# Generated by Django 3.1.12 on 2025-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productId',
            field=models.CharField(max_length=100),
        ),
    ]
