# Generated by Django 3.1.12 on 2025-05-26 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250525_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('totalCostCents', models.IntegerField()),
                ('products', models.JSONField()),
            ],
        ),
    ]
